---
  - hosts: all
    become: yes
    tasks:
  
      - name: Install Docker
        yum:
          name: docker
          state: present
  
      - name: Start and enable Docker service
        systemd:
          name: docker
          enabled: yes
          state: started
  
      - name: Update Yum repositories
        yum:
          name: "*"
          state: latest
  
      - name: Install unzip and wget
        yum:
          name:
            - unzip
            - wget
          state: present
  