---
- hosts: all
  become: yes
  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Update DNF repositories
      dnf:
        name: "*"
        state: latest

    - name: Install unzip and wget
      dnf:
        name:
          - unzip
          - wget
        state: present

    - name: Download SonarQube
      get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.1.69595.zip"
        dest: /tmp/sonarqube.zip

    - name: Extract SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes

    - name: Create SonarQube user
      user:
        name: sonarqube
        system: yes

    - name: Change ownership of SonarQube directory
      file:
        path: /opt/sonarqube-9.9.1.69595
        owner: sonarqube
        group: sonarqube
        state: directory
        recurse: yes

    - name: Set up SonarQube service
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking
          ExecStart=/opt/sonarqube-9.9.1.69595/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube-9.9.1.69595/bin/linux-x86-64/sonar.sh stop
          User=sonarqube
          Group=sonarqube
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start SonarQube service
      systemd:
        daemon_reload: yes
        name: sonarqube
        enabled: yes
        state: started
